# Generated by Django 5.2.2 on 2025-06-09 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoentry',
            options={'verbose_name': 'PhotoEntry', 'verbose_name_plural': 'PhotoEntry'},
        ),
    ]
