# Generated by Django 5.2.2 on 2025-06-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_photoentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoentry',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
